packages:
  - packages/*

ignoredBuiltDependencies:
  - 'cpu-features'
  - 'esbuild'
  - 'protobufjs'
  - 'ssh2'
  - 'unrs-resolver'

injectWorkspacePackages: true

# 2 days, in minutes
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - 'lucuma-core'
  - 'lucuma-schemas'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - 'prisma'

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160 # 2 weeks
