packages:
  - packages/*

injectWorkspacePackages: true

# 2 days, in minutes
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@gemini-hlsw/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - 'prisma'

ignoredBuiltDependencies:
  - 'cpu-features'
  - 'esbuild'
  - 'protobufjs'
  - 'ssh2'
  - 'unrs-resolver'

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160 # 2 weeks

blockExoticSubdeps: true
